# Generated by Django 3.1.2 on 2020-11-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201127_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fio',
            field=models.CharField(max_length=30, verbose_name='ФИО пользователя'),
        ),
    ]
