# Generated by Django 3.1.2 on 2020-11-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201120_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='users.district', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(default=1, on_delete=models.SET(None), to='users.region', verbose_name='Регион'),
        ),
    ]
