# Generated by Django 3.1.2 on 2022-10-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211011_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fio',
            field=models.CharField(max_length=70, verbose_name='ФИО пользователя'),
        ),
    ]
