# Generated by Django 3.1.2 on 2020-11-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201120_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'Возрастная катеогия', 'verbose_name_plural': 'Возрастная категория'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Округ', 'verbose_name_plural': 'Округа'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.age', verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.position', verbose_name='Должность'),
        ),
    ]
