# Generated by Django 3.1.2 on 2020-11-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201120_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Age',
            new_name='age',
        ),
    ]
