# Generated by Django 3.1.2 on 2021-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='existing',
            field=models.BooleanField(default=True, verbose_name='Существование'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='region',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Регион', 'Регион')], default='Москва', max_length=10, verbose_name='Регион'),
        ),
    ]
