# Generated by Django 3.1.2 on 2021-05-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_filexls'),
    ]

    operations = [
        migrations.AddField(
            model_name='filexls',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
