# Generated by Django 3.1.2 on 2021-05-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20210519_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filexls',
            name='processed',
            field=models.BooleanField(default=True, verbose_name='Обработано'),
        ),
    ]
