# Generated by Django 3.1.2 on 2021-05-26 09:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_auto_20210519_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('theme', models.CharField(max_length=200, verbose_name='Тема')),
                ('content', ckeditor.fields.RichTextField()),
                ('user', models.EmailField(max_length=254, verbose_name='Отправитель')),
            ],
        ),
    ]
