# Generated by Django 3.1.2 on 2021-05-26 10:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.CharField(default=1, max_length=15, verbose_name='Получатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
    ]
