# Generated by Django 3.1.2 on 2021-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_auto_20210526_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='region',
            field=models.CharField(choices=[('MSC', 'Москва и МО'), ('RG', 'Регион'), ('ALL', 'Все')], default='MSC', max_length=10, verbose_name='Регион'),
        ),
    ]
