# Generated by Django 3.1.2 on 2021-05-26 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0010_auto_20210526_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_email', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
