# Generated by Django 3.1.2 on 2021-07-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_auto_20210705_2146'),
        ('mailing', '0012_auto_20210712_1047'),
    ]

    operations = [
    ]
