# Generated by Django 3.1.2 on 2021-10-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_merge_20210713_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='region',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mailing.groupsubscribe', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
