# Generated by Django 3.1.2 on 2021-10-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_auto_20211005_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mailing.groupsubscribe', verbose_name='Группа'),
        ),
    ]
