# Generated by Django 3.1.2 on 2021-10-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0015_auto_20211005_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsubscribe',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группа'},
        ),
    ]
