# Generated by Django 3.1.2 on 2021-10-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0016_auto_20211005_1239'),
        ('mailing', '0016_auto_20211011_0924'),
    ]

    operations = [
    ]
