# Generated by Django 3.1.2 on 2021-10-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_merge_20211011_0927'),
        ('mailing', '0017_auto_20211014_1333'),
    ]

    operations = [
    ]
