# Generated by Django 3.2 on 2023-03-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0019_auto_20220112_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mailing.groupsubscribe', verbose_name='Группа'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email', 'group')},
        ),
    ]
