# Generated by Django 3.2 on 2023-04-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0020_auto_20230327_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filexls',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
