# Generated by Django 3.1.2 on 2021-03-16 09:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('video_url', models.URLField(verbose_name='Видео')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(verbose_name='Координаты'), max_length=100, size=None)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
                'managed': True,
            },
        ),
    ]
