# Generated by Django 3.1.2 on 2021-02-05 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image_url', models.URLField(verbose_name='Изображение')),
                ('video_url', models.URLField(verbose_name='Видео')),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(verbose_name='Координаты'), size=None)),
            ],
        ),
    ]
