# Generated by Django 3.1.2 on 2021-02-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placemark',
            name='image_url',
        ),
    ]
