# Generated by Django 3.1.2 on 2021-03-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placemark',
            options={'managed': True},
        ),
    ]
