# Generated by Django 3.1.2 on 2021-02-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_placemark_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemark',
            name='image_url',
            field=models.URLField(default=1, verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
