# Generated by Django 3.1.2 on 2022-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='participantevent',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_letter',
            field=models.BooleanField(default=False, verbose_name='Отправить письмо'),
        ),
    ]
