# Generated by Django 3.1.2 on 2022-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220907_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
    ]
