# Generated by Django 3.1.2 on 2022-09-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantevent',
            name='reg_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Регистрационный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantevent',
            name='event',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.PROTECT, to='event.event', verbose_name='Мероприятие'),
        ),
    ]
