# Generated by Django 3.1.2 on 2022-09-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0101_archive_participants'),
        ('event', '0004_auto_20220907_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantevent',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус участника'),
        ),
    ]
