# Generated by Django 3.1.2 on 2022-09-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220909_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantevent',
            options={'permissions': [('export_participants', 'Выгрузить список участников')], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
