# Generated by Django 3.1.2 on 2022-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20220912_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='content',
        ),
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
