# Generated by Django 3.1.2 on 2022-09-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20220922_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='broadcast_url',
            field=models.URLField(blank=True, null=True, verbose_name='Трансляция'),
        ),
    ]
