# Generated by Django 3.1.2 on 2022-10-04 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0010_event_broadcast_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participantevent',
            unique_together={('participant', 'event')},
        ),
    ]
