# Generated by Django 3.1.2 on 2022-10-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20221004_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
