# Generated by Django 3.1.2 on 2022-10-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_url',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
