# Generated by Django 3.1.2 on 2022-11-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0119_auto_20221026_1212'),
        ('event', '0016_auto_20221012_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantevent',
            name='status',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус участника'),
        ),
    ]
