# Generated by Django 3.2 on 2022-11-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20221107_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantevent',
            options={'permissions': [('export_participants', 'Выгрузить список участников'), ('send_selected_letter', 'Отправить письмо')], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
