# Generated by Django 3.2 on 2022-11-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_participantevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantevent',
            options={'permissions': [('export_participants', 'Выгрузить список участников'), ('send_selected_letter_to_participant_event', 'Отправить выбранное письмо')], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
