# Generated by Django 3.2 on 2023-05-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_participantevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
