# Generated by Django 3.2 on 2024-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantevent',
            name='presence',
            field=models.BooleanField(default=False, verbose_name='Присутствие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Очное', 'Очное'), ('Дистанционное', 'Дистанционное')], default='Дистанционное', max_length=20, verbose_name='Тип'),
        ),
    ]
