# Generated by Django 3.2 on 2024-10-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0163_auto_20241002_1834'),
        ('event', '0022_auto_20240218_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantevent',
            name='status',
            field=models.ForeignKey(blank=True, default=18, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус участника'),
        ),
    ]
