# Generated by Django 3.1.2 on 2021-03-31 07:55

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (конкурс/мероприятие)')),
                ('app', models.CharField(max_length=30, verbose_name='Приложение')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank', models.ImageField(storage=django.core.files.storage.FileSystemStorage, upload_to='certs/', verbose_name='Бланк сертификата')),
                ('size_font', models.IntegerField(verbose_name='Размер шрифта')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
                ('text_fio_coords', models.JSONField(default=list, verbose_name='Координаты ФИО')),
                ('text_reg_num_coords', models.JSONField(default=list, verbose_name='Координаты рег. номера')),
                ('text_status_coords', models.JSONField(blank=True, default=list, null=True, verbose_name='Координаты статуса')),
                ('text_level_coords', models.JSONField(blank=True, default=list, null=True, verbose_name='Координаты класса')),
                ('text_school_coords', models.JSONField(blank=True, default=list, null=True, verbose_name='Координаты обр. орг.')),
                ('contest', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.PROTECT, to='cert.events', verbose_name='Конкурс')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус участника')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
