# Generated by Django 3.1.2 on 2021-04-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название шрифта')),
                ('url', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cert',
            name='text_fio_coords',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='text_level_coords',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='text_reg_num_coords',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='text_school_coords',
        ),
        migrations.RemoveField(
            model_name='cert',
            name='text_status_coords',
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=50, verbose_name='Размер шрифта')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет текста')),
                ('position', models.JSONField(default=list, verbose_name='Позиция')),
                ('anchor', models.CharField(choices=[('ma', 'ma'), ('mt', 'mt'), ('mm', 'mm'), ('mb', 'mb'), ('md', 'md'), ('rs', 'rs'), ('ls', 'ls'), ('ms', 'ms')], default='ms', max_length=5)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cert.font', verbose_name='Шрифт')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текст',
            },
        ),
        migrations.AddField(
            model_name='cert',
            name='fio_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fio', to='cert.text', verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cert',
            name='level_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level', to='cert.text', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='cert',
            name='nomination_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomination', to='cert.text', verbose_name='Номинация'),
        ),
        migrations.AddField(
            model_name='cert',
            name='reg_num_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reg_num', to='cert.text', verbose_name='Регистрационный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cert',
            name='school_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='cert.text', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='cert',
            name='status_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='cert.text', verbose_name='Статус'),
        ),
    ]
