# Generated by Django 3.1.2 on 2021-04-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0002_auto_20210423_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='font',
            options={'verbose_name': 'Шрифт', 'verbose_name_plural': 'Шрифты'},
        ),
    ]
