# Generated by Django 3.1.2 on 2021-04-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0004_text_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='size_font',
        ),
        migrations.AlterField(
            model_name='cert',
            name='level_text',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='level', to='cert.text', verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cert',
            name='nomination_text',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nomination', to='cert.text', verbose_name='Номинация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cert',
            name='school_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='cert.text', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='status_text',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='cert.text', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
