# Generated by Django 3.1.2 on 2021-04-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0005_auto_20210423_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='level_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level', to='cert.text', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='nomination_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomination', to='cert.text', verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='status_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='cert.text', verbose_name='Статус'),
        ),
    ]
