# Generated by Django 3.1.2 on 2021-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0008_remove_text_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='anchor',
            field=models.CharField(choices=[('ma', 'ma'), ('mt', 'mt'), ('mm', 'mm'), ('mb', 'mb'), ('md', 'md'), ('rs', 'rs'), ('ls', 'ls'), ('ms', 'ms')], default='ms', max_length=5),
        ),
    ]
