# Generated by Django 3.1.2 on 2021-04-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0009_text_anchor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='anchor',
        ),
    ]
