# Generated by Django 3.1.2 on 2021-04-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0014_auto_20210429_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cert',
            old_name='position',
            new_name='position_text',
        ),
    ]
