# Generated by Django 3.1.2 on 2021-08-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0029_merge_20210812_1135'),
        ('cert', '0015_auto_20210429_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='contest',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.PROTECT, to='contests.events', verbose_name='Конкурс'),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
