# Generated by Django 3.1.2 on 2021-08-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0016_auto_20210812_1255'),
        ('cert', '0016_auto_20210812_1253'),
    ]

    operations = [
    ]
