# Generated by Django 3.1.2 on 2022-01-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0017_merge_20210812_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='article',
            field=models.CharField(default='22', max_length=7, verbose_name='Артикул'),
        ),
    ]
