# Generated by Django 3.1.2 on 2022-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0018_auto_20220112_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='year_contest',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Год'),
        ),
    ]
