# Generated by Django 3.1.2 on 2022-05-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0020_auto_20220506_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, null=True, verbose_name='Год'),
        ),
    ]
