# Generated by Django 3.1.2 on 2022-05-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0021_auto_20220506_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='author_name_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_name', to='cert.text', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cert',
            name='city_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city', to='cert.text', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='cert',
            name='teacher_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='cert.text', verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='school_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='cert.text', verbose_name='Организация'),
        ),
    ]
