# Generated by Django 3.1.2 on 2022-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0022_auto_20220512_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, null=True, verbose_name='Год'),
        ),
    ]
