# Generated by Django 3.1.2 on 2022-08-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0023_auto_20220810_0858'),
        ('cert', '0023_auto_20220815_1627'),
    ]

    operations = [
    ]
