# Generated by Django 3.2 on 2022-12-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0133_mymoskvichi_ovz'),
        ('cert', '0027_alter_cert_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='contest',
            field=models.ForeignKey(blank=True, default=None, max_length=15, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.events', verbose_name='Конкурс'),
        ),
    ]
