# Generated by Django 3.2 on 2022-12-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0028_alter_cert_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='name',
            field=models.CharField(blank=True, default='Мероприятие', max_length=200, null=True, verbose_name='Название'),
        ),
    ]
