# Generated by Django 3.2 on 2023-04-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0031_cert_event_name_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='event_name_text',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_name', to='cert.text', verbose_name='Название мероприятия'),
        ),
    ]
