# Generated by Django 3.2 on 2023-04-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0032_alter_cert_event_name_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='start_date_text',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_date', to='cert.text', verbose_name='Дата'),
        ),
    ]
