# Generated by Django 3.2 on 2023-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0033_cert_start_date_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='year_contest',
            field=models.CharField(default='2023-2024 год', max_length=20, null=True, verbose_name='Год'),
        ),
    ]
