# Generated by Django 3.2 on 2024-02-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0034_alter_cert_year_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='article',
            field=models.CharField(default='24', max_length=7, verbose_name='Артикул'),
        ),
    ]
