# Generated by Django 3.2 on 2024-10-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0163_auto_20241002_1834'),
        ('cert', '0035_alter_cert_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='status',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус участника'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='year_contest',
            field=models.CharField(default='2024-2025 год', max_length=20, null=True, verbose_name='Год'),
        ),
    ]
