# Generated by Django 3.2 on 2025-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0036_auto_20241002_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='article',
            field=models.CharField(default='25', max_length=7, verbose_name='Артикул'),
        ),
    ]
