# Generated by Django 3.2 on 2025-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0037_alter_cert_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='year_contest',
            field=models.CharField(default='2025-2026 год', max_length=20, null=True, verbose_name='Год'),
        ),
    ]
