# Generated by Django 3.2 on 2025-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urao', '0002_auto_20251220_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileurao',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(choices=[('30x20', '30 × 20'), ('40x30', '40 × 30'), ('50x40', '50 × 40'), ('60x40', '60 × 40'), ('60x50', '60 × 50'), ('70x50', '70 × 50'), ('70x55', '70 × 55'), ('70x60', '70 × 60'), ('80x60', '80 × 60'), ('80x65', '80 × 65'), ('80x70', '80 × 70'), ('90x60', '90 × 60'), ('90x70', '90 × 70'), ('100x70', '100 × 70'), ('100x80', '100 × 80'), ('100x90', '100 × 90'), ('120x100', '120 × 100'), ('150x100', '150 × 100'), ('150x120', '150 × 120')], default=1, max_length=10, verbose_name='Размер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileurao',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profileurao',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
    ]
