# Generated by Django 3.2 on 2026-05-02 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urao', '0006_auto_20260501_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileurao',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='О себе'),
        ),
    ]
