# Generated by Django 3.2 on 2026-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urao', '0007_alter_profileurao_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileurao',
            options={'ordering': ['order'], 'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
        migrations.AddField(
            model_name='profileurao',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Порядок'),
        ),
    ]
