# Generated by Django 3.1.2 on 2022-10-26 09:12

import ckeditor.fields
import contests.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('poster', models.ImageField(upload_to=contests.utils.PathAndRename('exposition/posters/'), verbose_name='Афиша')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес проведения')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
                ('start_date', models.DateField(verbose_name='Начало экспонирования')),
                ('end_date', models.DateField(verbose_name='Конец экспонирования')),
                ('archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('count_exp', models.IntegerField(verbose_name='Количество едениц')),
                ('count_participants', models.IntegerField(verbose_name='Количество участников')),
            ],
        ),
        migrations.CreateModel(
            name='ImageExposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=contests.utils.PathAndRename('exposition/images'), verbose_name='Изображение')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('crop_orientation_img', models.CharField(choices=[('top', 'Верх'), ('center', 'Центр'), ('bottom', 'Низ'), ('left', 'Лево'), ('right', 'Право')], default='center', max_length=50, verbose_name='Ориентация превью')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exposition.exposition')),
            ],
            options={
                'verbose_name': 'Изображение (Выставка)',
                'ordering': ['order_number'],
            },
        ),
    ]
