# Generated by Django 3.1.2 on 2022-10-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposition',
            options={'ordering': ['start_date'], 'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
        migrations.AlterModelOptions(
            name='imageexposition',
            options={'ordering': ['order_number'], 'verbose_name': 'Изображение (Выставка)', 'verbose_name_plural': 'Изображения для выставки'},
        ),
    ]
