# Generated by Django 3.1.2 on 2022-10-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0002_auto_20221026_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposition',
            options={'ordering': ['-start_date'], 'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
    ]
