# Generated by Django 3.2 on 2022-12-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0003_auto_20221029_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='virtual',
            field=models.BooleanField(default=False, verbose_name='Виртуальная'),
        ),
        migrations.AddField(
            model_name='imageexposition',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись'),
        ),
    ]
