# Generated by Django 3.2 on 2022-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0004_auto_20221207_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='publicate',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
