# Generated by Django 3.2 on 2022-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0005_exposition_publicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposition',
            name='publicate',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
