# Generated by Django 3.2 on 2022-12-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0006_alter_exposition_publicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageexposition',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exposition.exposition', verbose_name='Выставка'),
        ),
    ]
