# Generated by Django 3.2 on 2022-12-20 10:37

import contests.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0007_alter_imageexposition_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageexposition',
            name='image',
            field=models.ImageField(max_length=250, upload_to=contests.utils.PathAndRename('exposition/images'), verbose_name='Изображение'),
        ),
    ]
