# Generated by Django 3.2 on 2023-05-30 12:21
import csv
import datetime
from django.db import migrations


def insert(apps, schema_editor):
    data = []
    Exposition = apps.get_model('exposition', 'Exposition')
    ImageExposition = apps.get_model('exposition', 'ImageExposition')
    with open('./archive_expositions.csv', newline='') as file:
        rows = csv.reader(file, delimiter=',', quotechar='|')
        for i in rows:
            data.append(i)
    for item in data:
        print(item[6])
        e = Exposition(title=item[0], poster=item[3], address=item[1], content=item[2],
                       start_date=datetime.datetime.strptime(item[6].split('-')[0],
                                                             '%d.%m.%Y').date(),
                       end_date=datetime.datetime.strptime(item[6].split('-')[0],
                                                           '%d.%m.%Y').date(),
                       count_exp=55, count_participants=1000, archive=True
                       )
        e.save()
        for index in range(int(item[5])):
            obj = ImageExposition(image='{}{}.jpg'.format(item[4], index), images=e)
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('exposition', '0008_alter_imageexposition_image'),
    ]

    operations = [
        migrations.RunPython(insert)
    ]
