# Generated by Django 3.2 on 2023-09-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0009_auto_20230530_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposition',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1, verbose_name='Publication Status')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Контент')),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exposition.exposition', verbose_name='Выставка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
