# Generated by Django 3.2 on 2023-09-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0010_auto_20230928_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='exposition',
            options={'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
    ]
