# Generated by Django 3.2 on 2023-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0012_alter_comment_exposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=355, verbose_name='Автор'),
        ),
    ]
