# Generated by Django 3.2 on 2026-05-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposition', '0013_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposition',
            name='type',
            field=models.IntegerField(choices=[(1, 'Обычная выставка'), (2, 'УРАО')], default=1, verbose_name='Тип выставки'),
        ),
    ]
