# Generated by Django 3.2 on 2022-11-16 09:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=400, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Контент')),
            ],
        ),
    ]
