# Generated by Django 3.2 on 2022-11-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20221116_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(default=1, max_length=400, verbose_name='Подзаголовок'),
            preserve_default=False,
        ),
    ]
