# Generated by Django 3.2 on 2022-11-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_page_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Заголовок'),
        ),
    ]
