# Generated by Django 3.2 on 2023-08-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_category_publication_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('order',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
