# Generated by Django 3.2 on 2023-08-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_video_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(default='01022897d9054365b700159d8eb1ed23', verbose_name='Порядковый номер'),
        ),
    ]
