# Generated by Django 3.2 on 2023-08-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_video_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
