# Generated by Django 3.2 on 2023-08-10 11:00

import contests.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_video_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('link', models.URLField(null=True, verbose_name='Ссылка')),
                ('poster', models.ImageField(null=True, upload_to=contests.utils.PathAndRename('publication/posters/'), verbose_name='Обложка')),
                ('order', models.IntegerField(null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ('order',),
            },
        ),
    ]
