# Generated by Django 3.2 on 2023-08-10 11:01

import contests.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='order',
            field=models.IntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='poster',
            field=models.ImageField(upload_to=contests.utils.PathAndRename('publication/posters/'), verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
