# Generated by Django 3.2 on 2023-08-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_publication_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
