# Generated by Django 3.2 on 2023-08-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_publication_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(max_length=400, verbose_name='Ссылка'),
        ),
    ]
