# Generated by Django 3.2 on 2023-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_publication_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010')], default=1, max_length=10, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
