# Generated by Django 3.2 on 2023-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_video_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.CharField(default=1, max_length=255, verbose_name='Раздел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Порядковый номер'),
        ),
    ]
