# Generated by Django 3.2 on 2024-12-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20230921_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='contest_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Конкурс'),
        ),
    ]
