# Generated by Django 3.2 on 2025-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_publication_contest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='section',
            field=models.CharField(choices=[('artakiada', 'Артакиада'), ('mymoskvichi', 'Мы Москвичи'), ('all', 'Общий')], default='all', max_length=255, verbose_name='Раздел'),
        ),
    ]
