# Generated by Django 3.2 on 2025-06-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_video_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='video',
            name='section',
            field=models.CharField(choices=[('all', 'Общий'), ('artakiada', 'Артакиада'), ('mymoskvichi', 'Мы Москвичи')], default='all', max_length=255, verbose_name='Раздел'),
        ),
    ]
