# Generated by Django 3.1.2 on 2020-11-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=15, unique=True)),
                ('fio', models.CharField(blank=True, max_length=40, verbose_name='ФИО участника')),
                ('school', models.CharField(blank=True, max_length=150, verbose_name='Образовательная организация')),
                ('city', models.CharField(blank=True, max_length=101, verbose_name='Город')),
                ('year_contest', models.CharField(default='2020-2021 год', max_length=20, verbose_name='Год проведения')),
                ('date_reg', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Artakiada',
            fields=[
                ('basecontest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.basecontest')),
            ],
            options={
                'verbose_name': 'Участник АРТакиады',
                'verbose_name_plural': 'Участники АРТакиады',
            },
            bases=('contests.basecontest',),
        ),
        migrations.CreateModel(
            name='NRusheva',
            fields=[
                ('basecontest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.basecontest')),
                ('theme', models.CharField(blank=True, max_length=50)),
            ],
            bases=('contests.basecontest',),
        ),
    ]
