# Generated by Django 3.1.2 on 2020-10-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=15, unique=True)),
                ('date_reg', models.DateTimeField(auto_now=True)),
                ('school', models.CharField(blank=True, max_length=150, verbose_name='Образовательная организация')),
                ('fio', models.CharField(blank=True, max_length=40, verbose_name='ФИО участника')),
                ('city', models.CharField(blank=True, max_length=101, verbose_name='Город')),
                ('year_contest', models.CharField(default='2020-2021 год', max_length=20, verbose_name='Год проведения')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Округ')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Artakiada',
            fields=[
                ('basecontest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.basecontest')),
                ('info', models.CharField(blank=True, max_length=50)),
            ],
            bases=('contests.basecontest',),
        ),
        migrations.CreateModel(
            name='NRusheva',
            fields=[
                ('basecontest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.basecontest')),
                ('theme', models.CharField(blank=True, max_length=50)),
            ],
            bases=('contests.basecontest',),
        ),
        migrations.AddField(
            model_name='basecontest',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.district'),
        ),
        migrations.AddField(
            model_name='basecontest',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.region'),
        ),
        migrations.AddField(
            model_name='basecontest',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status'),
        ),
    ]
