# Generated by Django 3.1.2 on 2021-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichiselect',
            name='data',
            field=models.CharField(max_length=500, verbose_name='Данные'),
        ),
    ]
