# Generated by Django 3.1.2 on 2020-11-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20201118_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mymoskvichi',
            fields=[
                ('basecontest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.basecontest')),
            ],
            bases=('contests.basecontest',),
        ),
    ]
