# Generated by Django 3.1.2 on 2020-11-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20201127_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='barcode',
            field=models.CharField(default='0', max_length=5, verbose_name='Штрих-код'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='barcode',
            field=models.CharField(default='0', max_length=5, verbose_name='Штрих-код'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='barcode',
            field=models.CharField(default='0', max_length=5, verbose_name='Штрих-код'),
        ),
    ]
