# Generated by Django 3.1.2 on 2021-05-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20210429_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModxDbimgMuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('oldname', models.CharField(blank=True, db_column='oldName', max_length=255, null=True)),
                ('dateupload', models.CharField(blank=True, db_column='dateUpload', max_length=255, null=True)),
                ('competition1', models.CharField(blank=True, max_length=255, null=True)),
                ('picturename', models.CharField(blank=True, db_column='PictureName', max_length=255, null=True)),
                ('material', models.CharField(blank=True, db_column='Material', max_length=255, null=True)),
                ('fiocompetitor', models.CharField(blank=True, db_column='FioCompetitor', max_length=255, null=True)),
                ('agecompetitor', models.CharField(blank=True, db_column='ageCompetitor', max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('shcoolname', models.CharField(blank=True, db_column='shcoolName', max_length=255, null=True)),
                ('fioteacher', models.CharField(blank=True, db_column='FioTeacher', max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('temaname', models.CharField(blank=True, db_column='TemaName', max_length=255, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('sortage', models.IntegerField(blank=True, db_column='sortAge', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True)),
                ('cityname', models.CharField(blank=True, db_column='cityName', max_length=255, null=True)),
                ('pathfile', models.CharField(db_column='pathFile', max_length=255)),
                ('hesh', models.CharField(blank=True, max_length=255, null=True)),
                ('available', models.CharField(blank=True, db_column='Available', max_length=255, null=True)),
            ],
            options={
                'db_table': 'modx_dbimg_muz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Авторское название',
                'verbose_name_plural': 'Авторское название',
            },
        ),
        migrations.AlterField(
            model_name='mymoskvichiselect',
            name='data',
            field=models.CharField(max_length=255, verbose_name='Данные'),
        ),
        migrations.AddField(
            model_name='artakiada',
            name='author_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.authorname', verbose_name='Название'),
        ),
    ]
