# Generated by Django 3.1.2 on 2021-05-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20210513_1341'),
    ]

    operations = [
    
    ]
