# Generated by Django 3.1.2 on 2020-11-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20201127_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='barcode',
            field=models.CharField(max_length=15, verbose_name='Штрих-код'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='barcode',
            field=models.CharField(max_length=15, verbose_name='Штрих-код'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='barcode',
            field=models.CharField(max_length=15, verbose_name='Штрих-код'),
        ),
    ]
