# Generated by Django 3.1.2 on 2020-11-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201120_1401'),
        ('contests', '0003_mymoskvichi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artakiada',
            options={'verbose_name': 'АРТакиада (участник)', 'verbose_name_plural': 'АРТакиада (участники)'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статус'},
        ),
        migrations.AlterField(
            model_name='basecontest',
            name='city',
            field=models.CharField(max_length=101, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='basecontest',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='basecontest',
            name='fio',
            field=models.CharField(max_length=40, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='basecontest',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='basecontest',
            name='school',
            field=models.CharField(max_length=150, verbose_name='Образовательная организация'),
        ),
        migrations.AlterField(
            model_name='basecontest',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус'),
        ),
    ]
