# Generated by Django 3.1.2 on 2020-12-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок'),
        ),
    ]
