# Generated by Django 3.1.2 on 2021-05-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20210513_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeART',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема(Артакиада)',
                'verbose_name_plural': 'Темы(Артакиада)',
            },
        ),
        
        migrations.AddField(
            model_name='artakiada',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.themeart', verbose_name='Тема'),
        ),
    ]
