# Generated by Django 3.1.2 on 2020-11-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20201120_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/artakiada/'),
        ),
    ]
