# Generated by Django 3.1.2 on 2020-11-22 22:06

import contests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_artakiada_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='image',
            field=models.ImageField(upload_to=contests.models.PathAndRename('artakiada/')),
        ),
    ]
