# Generated by Django 3.1.2 on 2020-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20201127_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='fio_teacher',
            field=models.CharField(default=123123, max_length=40, verbose_name='ФИО педагога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='fio_teacher',
            field=models.CharField(default=3123123, max_length=40, verbose_name='ФИО педагога'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='fio_teacher',
            field=models.CharField(default=21312312, max_length=40, verbose_name='ФИО педагога'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='fio',
            field=models.CharField(max_length=40, verbose_name='Фамилия, имя'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio',
            field=models.CharField(max_length=40, verbose_name='Фамилия, имя'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio',
            field=models.CharField(max_length=40, verbose_name='Фамилия, имя'),
        ),
    ]
