# Generated by Django 3.1.2 on 2020-12-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_message_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
