# Generated by Django 3.1.2 on 2021-05-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20210514_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artakiada',
            name='author_name',
        ),
        migrations.DeleteModel(
            name='AuthorName',
        ),
    ]
