# Generated by Django 3.1.2 on 2020-12-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20201202_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymoskvichi',
            options={'verbose_name': 'Конкурс Мы Москвичи', 'verbose_name_plural': 'Конкурс Мы Москвичи'},
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Участник'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.mymoskvichi', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
