# Generated by Django 3.1.2 on 2020-12-03 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20201202_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymoskvichi',
            options={'verbose_name': 'Конкурс Мы Москвичи', 'verbose_name_plural': 'Конкурс Мы Москвичи'},
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.mymoskvichi', verbose_name='Участники')),
            ],
        ),
    ]
