# Generated by Django 3.1.2 on 2020-11-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20201128_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nrusheva',
            options={'verbose_name': 'Конкурс им. Нади Рушевой (участник)', 'verbose_name_plural': 'Конкурс им. Нади Рушевой (участники)'},
        ),
    ]
