# Generated by Django 3.1.2 on 2021-05-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20210517_1010'),
    ]

    operations = [

    ]
