# Generated by Django 3.1.2 on 2020-12-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20201203_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AddField(
            model_name='participant',
            name='participants',
            field=models.ForeignKey(default=656, on_delete=django.db.models.deletion.CASCADE, to='contests.mymoskvichi', verbose_name='Участники'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='fio',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
