# Generated by Django 3.1.2 on 2020-12-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20201209_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='MymoskvichiSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('nomination', 'Номинация'), ('age', 'Возраст'), ('theme', 'Тема')], max_length=20, verbose_name='Название поля')),
                ('data', models.CharField(max_length=50, verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='nomination',
            field=models.CharField(choices=[('1', '1')], default=1, max_length=30, verbose_name='Номинация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='fio_teacher',
            field=models.CharField(max_length=300, verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio_teacher',
            field=models.CharField(max_length=300, verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio_teacher',
            field=models.CharField(max_length=300, verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fio',
            field=models.CharField(max_length=50, verbose_name='Фамилия, имя'),
        ),
        migrations.CreateModel(
            name='TeacherExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('participants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.mymoskvichi', verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'Педагог',
                'verbose_name_plural': 'Педагоги',
            },
        ),
    ]
