# Generated by Django 3.1.2 on 2020-11-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.material', verbose_name='Материал'),
        ),
    ]
