# Generated by Django 3.1.2 on 2020-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20201203_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio',
            field=models.CharField(max_length=300, verbose_name='Участник'),
        ),
    ]
