# Generated by Django 3.1.2 on 2020-12-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_teacherextra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherextra',
            options={'verbose_name': 'Педагог', 'verbose_name_plural': 'Педагоги'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='fio',
            field=models.CharField(max_length=50, verbose_name='Фамилия, имя'),
        ),
    ]
