# Generated by Django 3.1.2 on 2020-12-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20201209_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='nomination',
        ),
    ]
