# Generated by Django 3.1.2 on 2021-05-20 10:51

import contests.models
from django.db import migrations, models

import contests.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20210517_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='image',
            field=models.ImageField(max_length=200, upload_to=contests.utils.PathAndRename('artakiada/'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='image',
            field=models.ImageField(max_length=200, upload_to=contests.utils.PathAndRename('nrusheva/'), verbose_name='Изображение'),
        ),
    ]
