# Generated by Django 3.1.2 on 2020-12-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20201204_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='participants',
            field=models.CharField(default=324, max_length=300, verbose_name='Участники'),
            preserve_default=False,
        ),
    ]
