# Generated by Django 3.1.2 on 2020-11-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20201122_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материал'},
        ),
    ]
