# Generated by Django 3.1.2 on 2020-12-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_remove_mymoskvichi_nomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='nomination',
            field=models.CharField(choices=[('1', '1')], default=1, max_length=30, verbose_name='Номинация'),
            preserve_default=False,
        ),
    ]
