# Generated by Django 3.1.2 on 2020-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20201209_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='fio_teacher',
            field=models.CharField(max_length=300, verbose_name='ФИО педагога'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio_teacher',
            field=models.CharField(max_length=300, verbose_name='ФИО педагога'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio_teacher',
            field=models.CharField(max_length=300, verbose_name='ФИО педагога'),
        ),
    ]
