# Generated by Django 3.1.2 on 2020-12-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_mymoskvichi_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='participants',
        ),
    ]
