# Generated by Django 3.1.2 on 2021-07-12 10:47

import contests.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0010_mymoskvichiselect_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('barcode', models.CharField(max_length=15, verbose_name='Штрих-код')),
                ('fio', models.CharField(max_length=300, verbose_name='Участник')),
                ('fio_teacher', models.CharField(max_length=300, verbose_name='Педагог')),
                ('school', models.CharField(max_length=150, verbose_name='Образовательная организация')),
                ('city', models.CharField(blank=True, max_length=101, verbose_name='Город')),
                ('date_reg', models.DateTimeField(auto_now=True)),
                ('contest', models.CharField(max_length=200, verbose_name='Конкурс')),
                ('year_contest', models.CharField(max_length=20, verbose_name='Год проведения')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to=contests.models.PathAndRename('all_contests/'), verbose_name='Изображение')),
                ('author_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Авторское название')),
                ('format', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3')], max_length=2, null=True, verbose_name='Формат работы')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Аннотация')),
                ('program', models.CharField(blank=True, max_length=100, null=True, verbose_name='Программа(ы), в которой выполнена работа')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на файл (облако)')),
                ('Participants', models.CharField(blank=True, max_length=500, null=True, verbose_name='Участники')),
                ('TeacherExtra', models.CharField(blank=True, max_length=300, null=True, verbose_name='Педагоги доп.')),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.age', verbose_name='Возраст')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.level', verbose_name='Класс')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.material', verbose_name='Материал')),
                ('nomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.nomination', verbose_name='Номинация')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.region', verbose_name='Регион')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.themeart', verbose_name='Тема')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
