# Generated by Django 3.1.2 on 2021-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_mymoskvichiselect_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения'),
        ),
    ]
