# Generated by Django 3.1.2 on 2020-12-09 21:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_mymoskvichi_nomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichi',
            name='nomination',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1')], max_length=30, verbose_name='Номинация'),
        ),
    ]
