# Generated by Django 3.1.2 on 2020-12-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_auto_20201209_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichi',
            name='nomination',
            field=models.CharField(choices=[('1', '1')], max_length=30, verbose_name='Номинация'),
        ),
    ]
