# Generated by Django 3.1.2 on 2020-11-23 13:04

import contests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_auto_20201123_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='image',
            field=models.ImageField(upload_to=contests.models.PathAndRename('artakiada/'), verbose_name='Изображение'),
        ),
    ]
