# Generated by Django 3.1.2 on 2021-07-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_auto_20210712_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='Participants',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='TeacherExtra',
            new_name='teacher_extra',
        ),
    ]
