# Generated by Django 3.1.2 on 2021-07-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20210712_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Архив', 'verbose_name_plural': 'Архив'},
        ),
    ]
