# Generated by Django 3.1.2 on 2020-12-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20201209_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='nomination_extra',
            field=models.CharField(choices=[('1', '1')], default=1, max_length=30, verbose_name='Доп.номинация'),
            preserve_default=False,
        ),
    ]
