# Generated by Django 3.1.2 on 2020-11-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20201123_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Номинация')),
            ],
            options={
                'verbose_name': 'Номинация',
                'verbose_name_plural': 'Номинация',
            },
        ),
        migrations.AddField(
            model_name='artakiada',
            name='nomination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.nomination', verbose_name='Номинация'),
        ),
    ]
