# Generated by Django 3.1.2 on 2021-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20210712_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='nomination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема'),
        ),
    ]
