# Generated by Django 3.1.2 on 2020-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_mymoskvichi_nomination_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='age',
            field=models.CharField(choices=[('1', '1')], max_length=2, null=True, verbose_name='Возрастная категория'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='author_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Авторское название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='program',
            field=models.CharField(max_length=100, null=True, verbose_name='Программа(ы), в которой выполнена работа'),
        ),
    ]
