# Generated by Django 3.1.2 on 2021-07-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_auto_20210712_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='city',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Город'),
        ),
    ]
