# Generated by Django 3.1.2 on 2020-12-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_auto_20201209_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на файл (облако)'),
        ),
    ]
