# Generated by Django 3.1.2 on 2021-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_auto_20210712_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Возраст'),
        ),
    ]
