# Generated by Django 3.1.2 on 2020-12-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_mymoskvichi_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichi',
            name='age',
            field=models.CharField(max_length=2, null=True, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='nomination',
            field=models.CharField(max_length=30, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='nomination_extra',
            field=models.CharField(max_length=30, verbose_name='Доп.номинация'),
        ),
    ]
