# Generated by Django 3.1.2 on 2020-12-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_auto_20201209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichi',
            name='age',
            field=models.CharField(max_length=50, null=True, verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='nomination',
            field=models.CharField(max_length=50, verbose_name='Номинация'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='nomination_extra',
            field=models.CharField(max_length=50, verbose_name='Доп.номинация'),
        ),
    ]
