# Generated by Django 3.1.2 on 2020-12-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_auto_20201209_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymoskvichi',
            options={'verbose_name': 'Конкурс Мы Москвичи (участники)', 'verbose_name_plural': 'Конкурс Мы Москвичи (участники)'},
        ),
        migrations.AlterModelOptions(
            name='mymoskvichiselect',
            options={'verbose_name': 'Список (Мы Москвичи)', 'verbose_name_plural': 'Списки (Мы Москвичи)'},
        ),
    ]
