# Generated by Django 3.1.2 on 2021-07-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_auto_20210705_2146'),
        ('contests', '0018_auto_20210713_1034'),
    ]

    operations = [
    ]
