# Generated by Django 3.1.2 on 2021-08-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_auto_20210713_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (конкурс/мероприятие)')),
                ('app', models.CharField(max_length=30, verbose_name='Приложение')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),

    ]
