# Generated by Django 3.1.2 on 2021-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_auto_20201209_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichiselect',
            name='data',
            field=models.CharField(max_length=255, verbose_name='Данные'),
        ),
    ]
