# Generated by Django 3.1.2 on 2021-08-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_auto_20210810_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contests.events', verbose_name='Конкурс/Мероприятие'),
            preserve_default=False,
        ),
    ]
