# Generated by Django 3.1.2 on 2021-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0020_theme_contest'),
    ]


#    operations = [
#        migrations.AlterField(
#            model_name='theme',
#            name='contest',
#            field=models.CharField(max_length=300, verbose_name='Конкурс/Мероприятие'),
#        ),
#    ]
