# Generated by Django 3.1.2 on 2021-08-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0022_auto_20210811_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeRUSH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема(Н.Рушева)',
                'verbose_name_plural': 'Темы(Н.Рушева)',
            },
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.themerush', verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
