# Generated by Django 3.1.2 on 2021-08-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0023_auto_20210811_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationMYMSK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номинация')),
            ],
            options={
                'verbose_name': 'Номинация',
                'verbose_name_plural': 'Номинация',
            },
        ),
        migrations.RenameModel(
            old_name='Nomination',
            new_name='NominationART',
        ),
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='nomination_extra',
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='nomination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.nominationmymsk', verbose_name='Номинация'),
        ),
    ]
