# Generated by Django 3.1.2 on 2021-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0025_auto_20210811_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeMYMSK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возраст(Мы Москвичи)',
                'verbose_name_plural': 'Возраст(Н.Рушева)',
            },
        ),
        migrations.RenameModel(
            old_name='Age',
            new_name='AgeRUSH',
        ),
        migrations.AlterModelOptions(
            name='agerush',
            options={'verbose_name': 'Возраст(Н.Рушева)', 'verbose_name_plural': 'Возраст(Н.Рушева)'},
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='Ссылка на файл (облако)'),
        ),
    ]
