# Generated by Django 3.1.2 on 2021-08-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0026_auto_20210811_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MymoskvichiSelect',
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.agemymsk', verbose_name='Возрастная категория'),
        ),
    ]
