# Generated by Django 3.1.2 on 2021-08-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0028_auto_20210812_1058'),
        ('contests', '0019_merge_20210713_1345'),
    ]

    operations = [
    ]
