# Generated by Django 3.1.2 on 2021-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0029_merge_20210812_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date_reg',
            field=models.DateTimeField(blank=True),
        ),
    ]
