# Generated by Django 3.1.2 on 2021-08-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0033_auto_20210818_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontest',
            name='type',
            field=models.CharField(choices=[(1, 'Конкурс'), (2, 'Мероприятие')], default=1, max_length=20, verbose_name='Тип'),
        ),
    ]
