# Generated by Django 3.1.2 on 2021-08-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0035_auto_20210818_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontest',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
