# Generated by Django 3.1.2 on 2021-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0037_auto_20210818_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showevent',
            name='name',
        ),
        migrations.AlterField(
            model_name='pagecontest',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть'),
        ),
    ]
