# Generated by Django 3.1.2 on 2021-08-19 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0038_auto_20210819_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontest',
            name='letter',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Письмо'),
        ),
    ]
