# Generated by Django 3.1.2 on 2021-08-19 09:53

import ckeditor.fields
import contests.models
from django.db import migrations, models

import contests.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0039_pagecontest_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontest',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='pagecontest',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=contests.utils.PathAndRename('PageContests/'), verbose_name='Логотип'),
        ),
    ]
