# Generated by Django 3.1.2 on 2021-09-06 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0040_auto_20210819_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='showevent',
            name='barcode',
            field=models.CharField(default=1, max_length=15, verbose_name='Штрих-код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showevent',
            name='city',
            field=models.CharField(blank=True, max_length=101, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='fio',
            field=models.CharField(default=1, max_length=300, verbose_name='Участник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showevent',
            name='fio_teacher',
            field=models.CharField(default=1, max_length=300, verbose_name='Педагог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showevent',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='school',
            field=models.CharField(default=1, max_length=150, verbose_name='Образовательная организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showevent',
            name='status',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='year_contest',
            field=models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='status',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='status',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='status',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='date_reg',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
