# Generated by Django 3.1.2 on 2021-09-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0042_auto_20210907_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontest',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало мероприятия'),
        ),
    ]
