# Generated by Django 3.1.2 on 2021-10-12 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20211011_0924'),
        ('contests', '0044_auto_20211005_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Возраст(Выставочные проекты)',
                'verbose_name_plural': 'Возраст(Выставочные проекты)',
            },
        ),
        migrations.CreateModel(
            name='LevelVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс(Выставочные проекты)',
                'verbose_name_plural': 'Класс(Выставочные проекты)',
            },
        ),
        migrations.CreateModel(
            name='NominationVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номинация')),
            ],
            options={
                'verbose_name': 'Номинация(Выставочные проекты)',
                'verbose_name_plural': 'Номинация(Выставочные проекты)',
            },
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.participant', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.teacherextra', verbose_name='Педагоги'),
        ),
        migrations.CreateModel(
            name='VP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('barcode', models.CharField(max_length=15, verbose_name='Штрих-код')),
                ('fio', models.CharField(max_length=300, verbose_name='Участник')),
                ('fio_teacher', models.CharField(max_length=300, verbose_name='Педагог')),
                ('school', models.CharField(max_length=150, verbose_name='Образовательная организация')),
                ('city', models.CharField(blank=True, max_length=101, verbose_name='Город')),
                ('year_contest', models.CharField(default='2021-2022 год', max_length=20, verbose_name='Год проведения')),
                ('date_reg', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=50, verbose_name='Авторское название')),
                ('activity_form', models.CharField(choices=[('1', 'Индивидуальный проект'), ('2', 'Коллективный проект')], max_length=50, verbose_name='Организационная форма')),
                ('activity_format', models.CharField(choices=[('2', 'Внеурочнный проект'), ('1', 'Урочный проект')], max_length=50, verbose_name='Формат проекта')),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.agevp', verbose_name='Возраст')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.levelvp', verbose_name='Класс')),
                ('nomination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.nominationvp', verbose_name='Номинация')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.region', verbose_name='Регион')),
                ('status', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
