# Generated by Django 3.1.2 on 2021-10-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0046_auto_20211013_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='teachers',
        ),
    ]
