# Generated by Django 3.1.2 on 2021-10-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0048_participantvp_teacherextravp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vp',
            options={'verbose_name': 'Конкурс Выставочных проектов (участники)', 'verbose_name_plural': 'Конкурс Выставочных проектов (участники)'},
        ),
        migrations.RemoveField(
            model_name='showevent',
            name='page_contest',
        ),
        migrations.AddField(
            model_name='archive',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='artakiada',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='pagecontest',
            name='alias',
            field=models.CharField(default='test', max_length=100, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='pagecontest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='vp',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='pagecontest',
            name='name',
            field=models.CharField(blank=True, default='test', max_length=150, verbose_name='Название мероприятия'),
        ),
    ]
