# Generated by Django 3.1.2 on 2021-10-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0049_auto_20211019_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='showevent',
            name='page_contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='page_contest_show_event', to='contests.pagecontest', verbose_name='Мероприятие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
    ]
