# Generated by Django 3.1.2 on 2021-10-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0050_auto_20211019_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': '', 'verbose_name_plural': 'Мероприятия для сертификатов'},
        ),
        migrations.AlterModelOptions(
            name='showevent',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
    ]
