# Generated by Django 3.1.2 on 2021-10-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0051_auto_20211019_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichi',
            name='info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
    ]
