# Generated by Django 3.1.2 on 2021-10-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0051_auto_20211019_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Информация'),
        ),
    ]
