# Generated by Django 3.1.2 on 2021-11-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0052_auto_20211020_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominationNR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номинация')),
            ],
            options={
                'verbose_name': 'Номинация(Н.Рушева)',
                'verbose_name_plural': 'Номинация(Н.Рушева)',
            },
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='birthday',
            field=models.DateField(default='2020-12-01', verbose_name='Дата Рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='nomination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.nominationnr', verbose_name='Номинация'),
        ),
    ]
