# Generated by Django 3.1.2 on 2021-10-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0053_auto_20211020_0052'),
        ('contests', '0052_auto_20211020_1135'),
    ]

    operations = [
    ]
