# Generated by Django 3.1.2 on 2021-11-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0053_auto_20211107_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrusheva',
            name='birthday',
            field=models.DateField(default='2020-12-01', verbose_name='Дата Рождения'),
        ),
    ]
