# Generated by Django 3.1.2 on 2021-11-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0054_auto_20211107_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrusheva',
            name='birthday',
            field=models.DateField(verbose_name='Дата Рождения'),
        ),
    ]
