# Generated by Django 3.1.2 on 2021-11-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0055_auto_20211107_2209'),
        ('contests', '0054_merge_20211020_1548'),
    ]

    operations = [
    ]
