# Generated by Django 3.1.2 on 2021-11-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0056_merge_20211107_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrusheva',
            name='info',
            field=models.ForeignKey(default=12, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
    ]
