# Generated by Django 3.1.2 on 2021-11-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0056_auto_20211108_1250'),
        ('contests', '0057_auto_20211108_2239'),
    ]

    operations = [
    ]
