# Generated by Django 3.1.2 on 2021-11-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0058_merge_20211109_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vp',
            name='activity_form',
        ),
        migrations.RemoveField(
            model_name='vp',
            name='activity_format',
        ),
        migrations.AddField(
            model_name='vp',
            name='direction',
            field=models.CharField(choices=[('1', 'Индивидуальный проект'), ('2', 'Коллективный проект'), ('3', 'Урочный проект')], default=1, max_length=50, verbose_name='Направление'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='info',
            field=models.ForeignKey(default=12, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='info',
            field=models.ForeignKey(default=13, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
    ]
