# Generated by Django 3.1.2 on 2021-11-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0059_auto_20211109_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление(Выставочные проекты)',
                'verbose_name_plural': 'Направление(Выставочные проекты)',
            },
        ),
        migrations.AlterField(
            model_name='vp',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.directionvp', verbose_name='Направление'),
        ),
    ]
