# Generated by Django 3.1.2 on 2021-11-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0058_auto_20211108_2301'),
        ('contests', '0060_auto_20211109_0852'),
    ]

    operations = [
    ]
