# Generated by Django 3.1.2 on 2021-11-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0060_auto_20211109_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmymoskvichi',
            name='birthday',
            field=models.DateField(default='2020-12-01', verbose_name='Дата Рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherextramymoskvichi',
            name='birthday',
            field=models.DateField(default='2020-12-01', verbose_name='Дата Рождения'),
            preserve_default=False,
        ),
    ]
