# Generated by Django 3.1.2 on 2021-11-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0061_auto_20211109_1407'),
        ('contests', '0061_merge_20211109_1003'),
    ]

    operations = [
    ]
