# Generated by Django 3.1.2 on 2021-11-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0065_auto_20211114_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agemymsk',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='info',
            field=models.ForeignKey(default=14, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
    ]
