# Generated by Django 3.1.2 on 2021-11-22 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0067_auto_20211122_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.themeart', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='participantmymoskvichi',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='teacherextramymoskvichi',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата Рождения'),
        ),
    ]
