# Generated by Django 3.1.2 on 2022-01-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0070_auto_20220120_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontest',
            name='name',
            field=models.CharField(blank=True, default='test', max_length=250, verbose_name='Название мероприятия'),
        ),
    ]
