# Generated by Django 3.1.2 on 2022-02-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0071_auto_20220121_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='app',
        ),
        migrations.RemoveField(
            model_name='events',
            name='model',
        ),
        migrations.AddField(
            model_name='events',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.pagecontest', verbose_name='Мероприятие'),
        ),
    ]
