# Generated by Django 3.1.2 on 2022-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0072_auto_20220211_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='level',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал'),
        ),
    ]
