# Generated by Django 3.1.2 on 2022-03-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0074_extraimagearchive_extraimagevp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimagearchive',
            name='extra_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contests.archive', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='extraimagevp',
            name='extra_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contests.vp', verbose_name='Изображения'),
        ),
    ]
