# Generated by Django 3.1.2 on 2022-03-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0075_auto_20220303_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='direction',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Направление'),
        ),
    ]
