# Generated by Django 3.1.2 on 2022-03-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0076_archive_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraimagearchive',
            options={'ordering': ['order_number'], 'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
    ]
