# Generated by Django 3.1.2 on 2022-03-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0077_auto_20220320_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='extraimagearchive',
            name='extra_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contests.archive'),
        ),
    ]
