# Generated by Django 3.1.2 on 2022-04-11 12:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0079_videoarchive_videovp'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='videoarchive',
            name='video',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='videovp',
            name='video',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
