# Generated by Django 3.1.2 on 2022-04-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0080_auto_20220411_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='fio',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Участник'),
        ),
    ]
