# Generated by Django 3.1.2 on 2022-04-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0082_auto_20220411_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=700, verbose_name='Участник'),
        ),
    ]
