# Generated by Django 3.1.2 on 2022-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0084_auto_20220411_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Райтинг'),
        ),
    ]
