# Generated by Django 3.1.2 on 2022-04-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0087_auto_20220412_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Архив', 'verbose_name_plural': 'Архив'},
        ),
    ]
