# Generated by Django 3.1.2 on 2022-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0088_auto_20220419_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='author_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Авторское название'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='author_name',
            field=models.CharField(max_length=700, verbose_name='Авторское название'),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['contest_name', 'nomination', '-rating'], name='contests_ar_contest_f255ef_idx'),
        ),
    ]
