# Generated by Django 3.1.2 on 2022-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0089_auto_20220422_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='rating',
            field=models.FloatField(blank=True, default=0, verbose_name='Райтинг'),
        ),
    ]
