# Generated by Django 3.1.2 on 2022-04-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0091_auto_20220422_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Райтинг'),
        ),
    ]
