# Generated by Django 3.1.2 on 2022-06-24 08:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0094_auto_20220425_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeTack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=50, verbose_name='Конкурс')),
                ('year_contest', models.CharField(max_length=50, verbose_name='Год')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема|Номинация')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Творческое задание',
                'verbose_name_plural': 'Творческие задания',
                'unique_together': {('contest_name', 'year_contest', 'theme')},
            },
        ),
    ]
