# Generated by Django 3.1.2 on 2022-08-10 08:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20211011_0924'),
        ('contests', '0095_creativetack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='content',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='info',
        ),
        migrations.AlterField(
            model_name='archive',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=700, null=True, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='fio_teacher',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Педагог'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='school',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Образовательная организация'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archive',
            name='year_contest',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='creativetack',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Контент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
    ]
