# Generated by Django 3.1.2 on 2022-08-15 16:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0095_creativetack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='creativetack',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Контент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='year_contest',
            field=models.CharField(default='2022-2023 год', max_length=20, verbose_name='Год проведения'),
        ),
    ]
