# Generated by Django 3.1.2 on 2022-08-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0097_auto_20220810_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date_reg',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
