# Generated by Django 3.1.2 on 2022-08-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0096_auto_20220815_1627'),
        ('contests', '0098_auto_20220810_0922'),
    ]

    operations = [
    ]
