# Generated by Django 3.1.2 on 2022-08-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0099_merge_20220817_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='crop_orientation_img',
            field=models.CharField(choices=[('top', 'Верх'), ('center', 'Центр'), ('bottom', 'Низ')], default='center', max_length=50, verbose_name='Ориентация превью'),
        ),
    ]
