# Generated by Django 3.1.2 on 2022-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0100_archive_crop_orientation_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='participants'),
        ),
    ]
