# Generated by Django 3.1.2 on 2022-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0101_archive_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraimagearchive',
            name='crop_orientation_img',
            field=models.CharField(choices=[('top', 'Верх'), ('center', 'Центр'), ('bottom', 'Низ')], default='center', max_length=50, verbose_name='Ориентация превью'),
        ),
    ]
