# Generated by Django 3.1.2 on 2022-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0103_auto_20220921_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='address_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес организации'),
        ),
        migrations.AddField(
            model_name='artakiada',
            name='phone_gir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='artakiada',
            name='snils_gir',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='СНИЛС'),
        ),
    ]
