# Generated by Django 3.1.2 on 2022-10-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0104_auto_20221020_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artakiada',
            old_name='address_school',
            new_name='address_school_gir',
        ),
    ]
