# Generated by Django 3.1.2 on 2022-10-20 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0105_auto_20221020_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата рождения'),
        ),
    ]
