# Generated by Django 3.1.2 on 2022-10-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0107_auto_20221020_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='city',
            field=models.CharField(max_length=101, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='city',
            field=models.CharField(max_length=101, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='city',
            field=models.CharField(max_length=101, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='city',
            field=models.CharField(max_length=101, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='city',
            field=models.CharField(max_length=101, verbose_name='Город'),
        ),
    ]
