# Generated by Django 3.1.2 on 2022-10-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0109_auto_20221020_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
