# Generated by Django 3.1.2 on 2022-10-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0110_auto_20221020_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='vp',
            name='ovz',
            field=models.BooleanField(default=False, verbose_name='Проекты, выполненные детьми с ОВЗ'),
        ),
    ]
