# Generated by Django 3.1.2 on 2022-10-21 10:00

import contests.utils
import contests.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0111_vp_ovz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vp',
            name='ovz',
            field=models.BooleanField(default=False, verbose_name='Проект, выполнен детьми с ОВЗ'),
        ),
        migrations.CreateModel(
            name='FileVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(max_length=200, upload_to=contests.utils.PathAndRename('file/'), validators=[contests.validators.validate_file_extension], verbose_name='Файл')),
                ('files', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contests.vp')),
            ],
            options={
                'verbose_name': 'Файлы (Аннотация|Презентация)',
                'verbose_name_plural': 'Файлы (Аннотация|Презентация)',
            },
        ),
    ]
