# Generated by Django 3.1.2 on 2022-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0112_auto_20221021_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vp',
            name='ovz',
            field=models.BooleanField(default=False, null=True, verbose_name='Проект, выполнен детьми с ОВЗ'),
        ),
    ]
