# Generated by Django 3.1.2 on 2022-10-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0114_auto_20221023_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vp',
            name='age',
        ),
        migrations.RemoveField(
            model_name='vp',
            name='level',
        ),
        migrations.AddField(
            model_name='vp',
            name='level',
            field=models.ManyToManyField(null=True, to='contests.LevelVP', verbose_name='Класс'),
        ),
    ]
