# Generated by Django 3.1.2 on 2022-10-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0115_auto_20221023_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vp',
            name='level',
            field=models.ManyToManyField(to='contests.LevelVP', verbose_name='Класс'),
        ),
    ]
