# Generated by Django 3.1.2 on 2022-10-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0117_auto_20221024_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vp',
            options={'permissions': [('export_participants', 'Выгрузить список участников')], 'verbose_name': 'Конкурс Выставочных проектов (участники)', 'verbose_name_plural': 'Конкурс Выставочных проектов (участники)'},
        ),
    ]
