# Generated by Django 3.1.2 on 2022-10-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0118_auto_20221024_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vp',
            options={'permissions': [('export_participants', 'Выгрузить список участников')], 'verbose_name': 'Конкурс Художественных проектов (участники)', 'verbose_name_plural': 'Конкурс Художественных проектов (участники)'},
        ),
    ]
