# Generated by Django 3.2 on 2022-11-09 12:34

import contests.utils
import contests.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0120_auto_20221109_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='description_file',
            field=models.FileField(max_length=200, null=True, upload_to=contests.utils.PathAndRename('file/'), validators=[contests.validators.validate_file_extension], verbose_name='Описание и сценарий'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='duration',
            field=models.CharField(blank=True, default='3:30', max_length=100, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='phone_gir',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Контактный телефон'),
        ),
    ]
