# Generated by Django 3.2 on 2022-11-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0122_alter_mymoskvichi_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmymoskvichi',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Дата Рождения'),
        ),
    ]
