# Generated by Django 3.2 on 2022-11-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0123_alter_participantmymoskvichi_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='vp',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
