# Generated by Django 3.2 on 2022-11-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0124_auto_20221110_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='vp',
            name='phone_gir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон'),
        ),
    ]
