# Generated by Django 3.2 on 2022-11-11 08:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0125_vp_phone_gir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantmymoskvichi',
            options={'verbose_name': 'Участник (Мы Москвичи)', 'verbose_name_plural': 'Участники (Мы Москвичи)'},
        ),
        migrations.AlterModelOptions(
            name='teacherextramymoskvichi',
            options={'verbose_name': 'Педагог (Мы Москвичи)', 'verbose_name_plural': 'Педагоги (Мы Москвичи)'},
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='phone_gir',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+7', max_length=128, null=True, region=None, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='participantmymoskvichi',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='participantmymoskvichi',
            name='fio',
            field=models.CharField(max_length=50, verbose_name='Фамилия Имя Отчество'),
        ),
    ]
