# Generated by Django 3.2 on 2022-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0130_alter_vp_ovz'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус создания'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус создания'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус создания'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус создания'),
        ),
        migrations.AddField(
            model_name='vp',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус создания'),
        ),
    ]
