# Generated by Django 3.2 on 2022-11-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0131_auto_20221117_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус изменения'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус изменения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус изменения'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус изменения'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='status_change',
            field=models.BooleanField(default=False, verbose_name='Статус изменения'),
        ),
    ]
