# Generated by Django 3.2 on 2022-11-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0132_auto_20221117_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='ovz',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', max_length=10, verbose_name='Проект, выполнен детьми с ОВЗ'),
        ),
    ]
