# Generated by Django 3.2 on 2022-12-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0133_mymoskvichi_ovz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontest',
            options={'ordering': ('-id',), 'verbose_name': 'Страница конкурса', 'verbose_name_plural': 'Страницы конкурса'},
        ),
        migrations.RemoveField(
            model_name='pagecontest',
            name='type',
        ),
        migrations.AlterField(
            model_name='pagecontest',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
