# Generated by Django 3.2 on 2022-12-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0134_auto_20221212_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontest',
            options={'verbose_name': 'Страница конкурса', 'verbose_name_plural': 'Страницы конкурсов'},
        ),
        migrations.AlterField(
            model_name='pagecontest',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть кнопку перехода'),
        ),
    ]
