# Generated by Django 3.2 on 2022-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0135_auto_20221213_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontest',
            name='name',
            field=models.CharField(blank=True, default='test', max_length=250, verbose_name='Название конкурса'),
        ),
        migrations.AddField(
            model_name='pagecontest',
            name='order',
            field=models.IntegerField('Порядковый номер', default=0),
        ),
            ]
