# Generated by Django 3.2 on 2022-12-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0136_alter_pagecontest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontest',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
