# Generated by Django 3.2 on 2022-12-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0137_alter_pagecontest_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontest',
            options={'ordering': ('order',), 'verbose_name': 'Страница конкурса', 'verbose_name_plural': 'Страницы конкурсов'},
        ),
    ]
