# Generated by Django 3.2 on 2023-01-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0138_alter_pagecontest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='fio',
            field=models.CharField(max_length=5000, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='fio',
            field=models.CharField(max_length=5000, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='fio',
            field=models.CharField(max_length=5000, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='fio',
            field=models.CharField(max_length=5000, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='fio',
            field=models.CharField(max_length=5000, verbose_name='Участник'),
        ),
    ]
