# Generated by Django 3.2 on 2023-01-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0139_auto_20230117_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='Участник'),
        ),
    ]
