# Generated by Django 3.2 on 2023-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0140_alter_archive_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vp',
            name='author_name',
            field=models.CharField(max_length=200, verbose_name='Авторское название'),
        ),
    ]
