# Generated by Django 3.2 on 2023-03-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0141_alter_vp_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Проект "Дизайн детям"',
                'verbose_name_plural': 'проекты "Дизайн детям"',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contests.archive',),
        ),
    ]
