# Generated by Django 3.2 on 2023-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0142_archiveproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantvp',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='participantvp',
            name='level',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='participantvp',
            name='snils_gir',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='participantvp',
            name='fio',
            field=models.CharField(max_length=50, verbose_name='Фамилия, имя, отчество'),
        ),
    ]
