# Generated by Django 3.2 on 2023-05-26 12:09
import csv
from django.db import migrations


def update(apps, schema_editor):
    data = []
    Archive = apps.get_model('contests', 'Archive')
    with open('./data_mm_2022.csv', newline='') as file:
        rows = csv.reader(file, delimiter=',', quotechar=',')
        for i in rows:
            data.append(i)
    for i in data:
        obj = Archive.objects.filter(reg_number=i[1])
        if obj:
            obj[0].link = i[0]
            obj[0].publish = True
            obj[0].save()


class Migration(migrations.Migration):
    dependencies = [
        ('contests', '0143_auto_20230425_1513'),
    ]

    operations = [
        migrations.RunPython(update)
    ]
