# Generated by Django 3.2 on 2023-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0147_alter_creativetack_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='year_contest',
            field=models.CharField(default='2023-2024 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='year_contest',
            field=models.CharField(default='2023-2024 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='year_contest',
            field=models.CharField(default='2023-2024 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='year_contest',
            field=models.CharField(default='2023-2024 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='year_contest',
            field=models.CharField(default='2023-2024 год', max_length=20, verbose_name='Год проведения'),
        ),
    ]
