# Generated by Django 3.2 on 2023-08-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0148_auto_20230801_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name': 'Архив', 'verbose_name_plural': 'Архив'},
        ),
    ]
