# Generated by Django 3.2 on 2023-08-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0149_alter_archive_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-rating', 'reg_number'], 'verbose_name': 'Архив', 'verbose_name_plural': 'Архив'},
        ),
    ]
