# Generated by Django 3.2 on 2023-10-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0150_alter_archive_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artakiada',
            options={'verbose_name': 'Конкурс АРТакиада', 'verbose_name_plural': 'Конкурс АРТакиада'},
        ),
        migrations.AlterModelOptions(
            name='mymoskvichi',
            options={'verbose_name': 'Конкурс Мы Москвичи', 'verbose_name_plural': 'Конкурс Мы Москвичи'},
        ),
        migrations.AlterModelOptions(
            name='nrusheva',
            options={'verbose_name': 'Конкурс им. Нади Рушевой', 'verbose_name_plural': 'Конкурс им. Нади Рушевой'},
        ),
        migrations.AlterModelOptions(
            name='vp',
            options={'permissions': [('export_participants', 'Выгрузить список участников')], 'verbose_name': 'Конкурс АРТ-проект', 'verbose_name_plural': 'Конкурс АРТ-проект'},
        ),
        migrations.AddField(
            model_name='artakiada',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='mymoskvichi',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='showevent',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='vp',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.level', verbose_name='Класс общеобразовательной школы'),
        ),
    ]
