# Generated by Django 3.2 on 2023-10-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0152_auto_20231009_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artakiada',
            options={'verbose_name': 'Заявка(у) на участие', 'verbose_name_plural': 'Конкурс АРТакиада «Изображение и слово»'},
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.themeart', verbose_name='Тема 1 тур'),
        ),
        migrations.AlterUniqueTogether(
            name='artakiada',
            unique_together={('fio', 'level', 'theme', 'age', 'author_name', 'image')},
        ),
    ]
