# Generated by Django 3.2 on 2023-10-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0153_auto_20231012_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artakiada',
            unique_together={('fio', 'level', 'age', 'image')},
        ),
    ]
