# Generated by Django 3.2 on 2023-10-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0154_alter_artakiada_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artakiada',
            unique_together={('fio', 'level', 'age', 'theme', 'fio_teacher')},
        ),
    ]
