# Generated by Django 3.2 on 2023-10-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0155_alter_artakiada_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artakiada',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='artakiada',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='artakiada',
            name='sur_name',
        ),
    ]
