# Generated by Django 3.2 on 2023-10-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0156_auto_20231012_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vp',
            options={'permissions': [('export_participants', 'Выгрузить список участников')], 'verbose_name': 'Заявка(у) на участие', 'verbose_name_plural': 'Конкурс АРТ-проект'},
        ),
        migrations.AddField(
            model_name='vp',
            name='organization_form',
            field=models.CharField(choices=[('Индивидуальный', 'Индивидуальный'), ('Коллективный', 'Коллективный')], default=1, max_length=100, verbose_name='Форма организации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vp',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.directionvp', verbose_name='Направление'),
        ),
    ]
