# Generated by Django 3.2 on 2023-11-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0159_alter_vp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymoskvichi',
            options={'verbose_name': 'Заявка(у) на участие', 'verbose_name_plural': 'Конкурс Мы Москвичи'},
        ),
        migrations.AlterModelOptions(
            name='nrusheva',
            options={'verbose_name': 'Заявка(у) на участие', 'verbose_name_plural': 'Конкурс им. Нади Рушевой'},
        ),
        migrations.AddField(
            model_name='participantmymoskvichi',
            name='level',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.level', verbose_name='Класс общеобразовательной школы'),
        ),
        migrations.AlterUniqueTogether(
            name='nrusheva',
            unique_together={('fio', 'level', 'age', 'theme', 'fio_teacher')},
        ),
    ]
