# Generated by Django 3.2 on 2023-11-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0160_auto_20231107_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artakiada',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nrusheva',
            unique_together=set(),
        ),
    ]
