# Generated by Django 3.2 on 2023-11-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0161_auto_20231117_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmymoskvichi',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.mymoskvichi', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='participantvp',
            name='participants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.vp', verbose_name='Участники'),
        ),
    ]
