# Generated by Django 3.2 on 2024-10-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0162_auto_20231121_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artakiada',
            name='consent_personal_data',
        ),
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='consent_personal_data',
        ),
        migrations.RemoveField(
            model_name='nrusheva',
            name='consent_personal_data',
        ),
        migrations.RemoveField(
            model_name='showevent',
            name='consent_personal_data',
        ),
        migrations.RemoveField(
            model_name='vp',
            name='consent_personal_data',
        ),
        migrations.AddField(
            model_name='participantvp',
            name='agent_participant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail родителя/законного представителя'),
        ),
        migrations.AddField(
            model_name='participantvp',
            name='agent_participant_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон родителя/законного представителя'),
        ),
        migrations.AddField(
            model_name='participantvp',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных участника'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='info',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='year_contest',
            field=models.CharField(default='2024-2025 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='info',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='year_contest',
            field=models.CharField(default='2024-2025 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='info',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='year_contest',
            field=models.CharField(default='2024-2025 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='year_contest',
            field=models.CharField(default='2024-2025 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='info',
            field=models.ForeignKey(default=57, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.pagecontest'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='year_contest',
            field=models.CharField(default='2024-2025 год', max_length=20, verbose_name='Год проведения'),
        ),
    ]
