# Generated by Django 3.2 on 2024-10-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0163_auto_20241002_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных участника'),
        ),
    ]
