# Generated by Django 3.2 on 2024-11-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0165_auto_20241011_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrusheva',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='nrusheva',
            name='phone_parent_gir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон родителя'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='phone_gir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон педагога'),
        ),
    ]
