# Generated by Django 3.2 on 2024-11-14 20:01

import contests.utils
import contests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0166_auto_20241103_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='mymoskvichi',
            name='ovz',
        ),
        migrations.AddField(
            model_name='participantmymoskvichi',
            name='agent_participant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail родителя/законного представителя'),
        ),
        migrations.AddField(
            model_name='participantmymoskvichi',
            name='agent_participant_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон родителя/законного представителя'),
        ),
        migrations.AddField(
            model_name='participantmymoskvichi',
            name='consent_personal_data',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных участника'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='description_file',
            field=models.FileField(max_length=200, null=True, upload_to=contests.utils.PathAndRename('file/'), validators=[contests.validators.validate_file_extension], verbose_name='ПРЕСС-КИТ'),
        ),
    ]
