# Generated by Django 3.2 on 2024-11-14 20:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0167_auto_20241114_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='phone_gir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='phone_gir',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+7', max_length=128, null=True, region=None, verbose_name='Контактный телефон педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='phone_gir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Электронная почта педагога/руководителя'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='phone_gir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный телефон педагога/руководителя'),
        ),
    ]
