# Generated by Django 3.2 on 2024-11-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0168_auto_20241114_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='format',
            field=models.CharField(choices=[('ФИЛЬМ', 'ФИЛЬМ'), ('МУЛЬТИПЛИКАЦИЯ (АНИМАЦИЯ)', 'МУЛЬТИПЛИКАЦИЯ (АНИМАЦИЯ)'), ('ПРЕЗЕНТАЦИЯ', 'ПРЕЗЕНТАЦИЯ')], default=1, max_length=35, verbose_name='Формат работы'),
            preserve_default=False,
        ),
    ]
