# Generated by Django 3.2 on 2025-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0169_mymoskvichi_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='format',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3')], max_length=50, null=True, verbose_name='Формат работы'),
        ),
    ]
