# Generated by Django 3.2 on 2025-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0170_alter_archive_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveProxy',
        ),
        migrations.CreateModel(
            name='DesignArchiveProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Проект "Дизайн детям"',
                'verbose_name_plural': 'проекты "Дизайн детям"',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contests.archive',),
        ),
        migrations.CreateModel(
            name='KultNasArchiveProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Культурное наследие',
                'verbose_name_plural': 'Культурное наследие',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contests.archive',),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='year_contest',
            field=models.CharField(default='2025-2026 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='year_contest',
            field=models.CharField(default='2025-2026 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='year_contest',
            field=models.CharField(default='2025-2026 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='year_contest',
            field=models.CharField(default='2025-2026 год', max_length=20, verbose_name='Год проведения'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='year_contest',
            field=models.CharField(default='2025-2026 год', max_length=20, verbose_name='Год проведения'),
        ),
    ]
