# Generated by Django 3.2 on 2025-10-05 17:54

import contests.utils
import contests.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0171_auto_20250912_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantvp',
            name='consent_non_commercial_use',
            field=models.BooleanField(default=True, verbose_name='Согласие на некоммерческое использование конкурсной работы'),
        ),
        migrations.AddField(
            model_name='participantvp',
            name='file_consent_non_commercial_use',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=contests.utils.PathAndRename('file/'), validators=[contests.validators.validate_file_extension], verbose_name='Файл (Согласие 2)'),
        ),
        migrations.AddField(
            model_name='participantvp',
            name='file_consent_personal_data',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=contests.utils.PathAndRename('file/'), validators=[contests.validators.validate_file_extension], verbose_name='Файл (Согласие 1)'),
        ),
        migrations.AlterField(
            model_name='levelvp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Класс'),
        ),
    ]
