# Generated by Django 3.2 on 2025-10-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0172_auto_20251005_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymoskvichi',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.thememymsk', verbose_name='Тема'),
        ),
    ]
