# Generated by Django 3.2 on 2025-10-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0173_mymoskvichi_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelvp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Возрастная категория'),
        ),
    ]
