# Generated by Django 3.2 on 2025-10-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0174_alter_levelvp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vp',
            name='level',
            field=models.ManyToManyField(related_name='levels', to='contests.LevelVP', verbose_name='Возрастная категория'),
        ),
    ]
