# Generated by Django 3.2 on 2025-10-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_fio'),
        ('contests', '0175_alter_vp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ (г. Москва)'),
        ),
        migrations.AlterField(
            model_name='mymoskvichi',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ (г. Москва)'),
        ),
        migrations.AlterField(
            model_name='nrusheva',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ (г. Москва)'),
        ),
        migrations.AlterField(
            model_name='showevent',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ (г. Москва)'),
        ),
        migrations.AlterField(
            model_name='vp',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.district', verbose_name='Округ (г. Москва)'),
        ),
    ]
