# Generated by Django 3.2 on 2025-10-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0176_auto_20251024_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='artakiada',
            name='author_name',
            field=models.CharField(max_length=150, verbose_name='Авторское название'),
        ),
    ]
