# Generated by Django 3.2 on 2025-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0177_auto_20251024_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='artakiada',
            name='type_book_illustration',
            field=models.CharField(choices=[('spread', ' Разворот книги'), ('illustration', 'Иллюстрация')], default='spread', max_length=20, verbose_name='Тип книжной иллюстрации'),
        ),
    ]
