# Generated by Django 3.2 on 2025-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0178_artakiada_type_book_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artakiada',
            name='type_book_illustration',
            field=models.CharField(choices=[('spread', ' Разворот книги'), ('illustration', 'Иллюстрация')], max_length=20, null=True, verbose_name='Тип книжной иллюстрации'),
        ),
    ]
