# Generated by Django 3.2 on 2025-12-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0179_alter_artakiada_type_book_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymoskvichi',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.thememymsk', verbose_name='Тема'),
        ),
    ]
